/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import com.lowagie.text.pdf.PdfDictionary;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import traitement.Bmp;

/**
 *
 * @author Immortel
 */
public class Rapport extends javax.swing.JPanel {

    /**
     * Creates new form Rapport
     */
    Bmp b = new Bmp();

    public Rapport() {
        initComponents();
        b.color(jPanel1, jPanel2);
        print.setText("Imprimer les rapports");
        id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        presence = new javax.swing.JLabel();
        offre = new javax.swing.JLabel();
        carte = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        agent = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPRESSION DES DOCUMENTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 41));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        presence.setBackground(new java.awt.Color(1, 163, 184));
        presence.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        presence.setText("Liste des présences");
        presence.setToolTipText("cliquez ici pour voir la liste de présence");
        presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        presence.setOpaque(true);
        presence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presenceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                presenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                presenceMouseExited(evt);
            }
        });
        jPanel2.add(presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 160, 30));

        offre.setBackground(new java.awt.Color(1, 163, 184));
        offre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        offre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        offre.setText("Ofrre");
        offre.setToolTipText("cliquez pour voir les offres");
        offre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        offre.setOpaque(true);
        offre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                offreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                offreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                offreMouseExited(evt);
            }
        });
        jPanel2.add(offre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 30));

        carte.setBackground(new java.awt.Color(1, 163, 184));
        carte.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        carte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carte.setText("Carte de service");
        carte.setToolTipText("cliquez ici pour voir les cartes à imprimer");
        carte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        carte.setOpaque(true);
        carte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carteMouseExited(evt);
            }
        });
        jPanel2.add(carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 30));

        print.setBackground(new java.awt.Color(1, 163, 184));
        print.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Imprimer les rapports");
        print.setToolTipText("cliquez ici pour i,pri,er les rapports");
        print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        print.setOpaque(true);
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        jPanel2.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 30));

        date2.setDateFormatString("yyyy-MM-dd");
        date2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date2PropertyChange(evt);
            }
        });
        jPanel2.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 190, 30));

        date1.setDateFormatString("yyyy-MM-dd");
        date1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date1PropertyChange(evt);
            }
        });
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 940, 400));

        agent.setBackground(new java.awt.Color(1, 163, 184));
        agent.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        agent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent.setText("Liste des agents");
        agent.setToolTipText("cliquez ici pour voir la liste des agents");
        agent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        agent.setOpaque(true);
        agent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agentMouseExited(evt);
            }
        });
        jPanel2.add(agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 160, 30));
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 30, 10));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 960, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void presenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presenceMouseClicked
        b.chargement(jTable1, "select * from presence");
        print.setText("Imprimer les présence");
        id.setText("");
    }//GEN-LAST:event_presenceMouseClicked

    private void carteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteMouseClicked
        b.chargement(jTable1, "select * from v_carte");
        print.setText("Imprimer la Carte");
        id.setText("");

    }//GEN-LAST:event_carteMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        String req = "SELECT Id, concat(NOM, ' ',POSTNOM,' ',PRENOM) Noms,SEXE,date_naiss AS [DATE_DE_NAISS], DATEDIFF(YEAR,date_naiss, GETDATE()) AS AGE, etat_civil\n"
                + "	[ETAT CIVIL], NATIONALITE, ADRESSE, TELEPHONE, niv_etude [NIVEAU D'ETUDE],PHOTO,QrCode,Matricule FROM agent where ID ='" + id.getText() + "'",
                req2 = "select a.id,ref_offre,qualite,experience,niveau,date_depot,designation_fonct, format(GETDATE(),'yyyy-MM-dd HH:mm:ss') as date_publication, concat(DATEDIFF(DAY, GETDATE(),date_depot),' Jours') as DUREE from APPARTENIR a\n"
                + "inner join OFFRE o on o.id= a.codeoffre inner join fonction f on f.Id_fonction=a.codefonction where a.id='" + id.getText() + "'",
                req3 = "select PRESENCE.ID,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_SORTIE,ACTION,abs(dbo.f_heure()) HEURE,abs(dbo.f_min()) _MIN,(NOM+' '+ POSTNOM) NOMS from presence JOIN AGENT ON AGENT.ID= PRESENCE.CODEAGENT where date_presence between '" + ((JTextField) date1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) date2.getDateEditor().getUiComponent()).getText() + "'",
                req4 = "SELECT id,CONCAT(NOM, ' ',POSTNOM, ' ',PRENOM) as NOMS, SEXE,etat_civil\n"
                + "	[ETAT CIVIL], ADRESSE, TELEPHONE, niv_etude [NIVEAU D'ETUDE], Nationalite FROM agent";
        if (!(id.getText().isEmpty()) && print.getText().equals("Imprimer la Carte")) {
            b.EtatSortie(req, "Carte");
            id.setText("");
            print.setText("Imprimer les rapports");
        } else if (!(id.getText().isEmpty()) && print.getText().equals("Imprimmer Offre")) {
            b.EtatSortie(req2, "Offre");
            id.setText("");
            print.setText("Imprimer les rapports");
        } else if ((!(((JTextField) date1.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) date2.getDateEditor().getUiComponent()).getText().isEmpty())) && print.getText().equals("Imprimer les présence")) {
            b.EtatSortie(req3, "ListePresence");
            id.setText("");
            print.setText("Imprimer les rapports");
        } else if (print.getText().equals("Imprimmer liste agent")) {
            b.EtatSortie(req4, "Agent");
            id.setText("");
            print.setText("Imprimer les rapports");
        } else {
            JOptionPane.showMessageDialog(null, "Vérifier si vous n'avez pas oublier de \nselectionner un element ou soit \nles dates pour la presence");
            id.setText("");
            print.setText("Imprimer les rapports");
        }
    }//GEN-LAST:event_printMouseClicked

    private void agentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentMouseClicked
        b.chargement(jTable1, "select * from v_agent");
        print.setText("Imprimmer liste agent");
        id.setText("");
    }//GEN-LAST:event_agentMouseClicked

    private void offreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offreMouseClicked
        b.chargement(jTable1, "select * from v_offre");
        print.setText("Imprimmer Offre");
        id.setText("");
    }//GEN-LAST:event_offreMouseClicked

    private void date1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date1PropertyChange
        b.recherche(jTable1, "select * from presence where date_presence between '" + ((JTextField) date1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) date2.getDateEditor().getUiComponent()).getText() + "'");
        id.setText("");
    }//GEN-LAST:event_date1PropertyChange

    private void date2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date2PropertyChange
        b.recherche(jTable1, "select * from presence where date_presence between '" + ((JTextField) date1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) date2.getDateEditor().getUiComponent()).getText() + "'");
        id.setText("");
    }//GEN-LAST:event_date2PropertyChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (print.getText().equals("Imprimmer liste agent")) {
            b.deplacement("v_agent", id, jTable1);
        } else if (print.getText().equals("Imprimmer Offre")) {
            b.deplacement("v_offre", id, jTable1);
        } else if (print.getText().equals("Imprimer la Carte")) {
            b.deplacement("v_carte", id, jTable1);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void offreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offreMouseEntered
        b.entree_colorlabel(offre);
    }//GEN-LAST:event_offreMouseEntered

    private void offreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offreMouseExited
        b.exitcolorlabel(offre);
    }//GEN-LAST:event_offreMouseExited

    private void carteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteMouseEntered
        b.entree_colorlabel(carte);
    }//GEN-LAST:event_carteMouseEntered

    private void carteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteMouseExited
        b.exitcolorlabel(carte);
    }//GEN-LAST:event_carteMouseExited

    private void agentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentMouseEntered
        b.entree_colorlabel(agent);
    }//GEN-LAST:event_agentMouseEntered

    private void agentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentMouseExited
        b.exitcolorlabel(agent);
    }//GEN-LAST:event_agentMouseExited

    private void presenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presenceMouseEntered
        b.entree_colorlabel(presence);
    }//GEN-LAST:event_presenceMouseEntered

    private void presenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presenceMouseExited
        b.exitcolorlabel(presence);
    }//GEN-LAST:event_presenceMouseExited

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        b.entree_colorlabel(print);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        b.exitcolorlabel(print);
    }//GEN-LAST:event_printMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent;
    private javax.swing.JLabel carte;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel offre;
    private javax.swing.JLabel presence;
    private javax.swing.JLabel print;
    // End of variables declaration//GEN-END:variables
}
